const projectData = [
  {
    image: './req/1.png',
    projectname: 'Fast Lane Racers',
    field: 'Full-Stack-Project',
    technologies: ['bx bxl-html5', 'bx bxl-css3', 'bx bxl-javascript', 'bx bxl-react', 'bx bxl-postgresql'],
    description: 'Full stack app for Swift car booking, reserve rides by date and city for dependable travel experiences.',
    livelink: '',
    sourcelink: '',
  },
  {
    image: './req/Weather.png',
    projectname: 'Weather360',
    field: 'React-Redux-Project',
    technologies: ['bx bxl-html5', 'bx bxl-css3', 'bx bxl-javascript', 'bx bxl-react', 'bx bxl-redux'],
    description: 'Weather360 is a robust web application that offers precise weather information for cities worldwide',
    livelink: '',
    sourcelink: '',
  },
  {
    image: './req/space-traveller.png',
    projectname: 'Space Traveller',
    field: 'React-Redux-Project',
    technologies: ['bx bxl-html5', 'bx bxl-css3', 'bx bxl-javascript', 'bx bxl-react', 'bx bxl-redux'],
    description: 'React and Redux web app utilizing SpaceX API for rocket and mission info, reservations, and profiles.',
    livelink: '',
    sourcelink: '',
  },
  {
    image: './req/Bugzilla.avif ',
    projectname: 'Quote Editor',
    field: 'Turbo-Rails',
    technologies: ['bx bxl-tailwind-css', 'devicon-rails-plain colored', 'devicon-postgresql-plain-wordmark', 'bx bxl-react'],
    description: 'Turbo Rails quote editor with minimal JS. Users can manage quotes and items, with dynamic total updates.',
    livelink: '',
    sourcelink: '',
  },
  {
    image: './req/Capstone.png',
    projectname: 'Fast Lane Racers',
    field: 'JavaScript-Project',
    technologies: ['bx bxl-html5', 'bx bxl-css3', 'bx bxl-javascript'],
    description: 'FilmFussion: Web hub for TV and movies with user ratings, reviews, and interactive community features.',
    livelink: '',
    sourcelink: '',
  },
  {
    image: './req/Bugzilla.png',
    projectname: 'Bugzilla Project',
    field: 'Rails-React-Project',
    technologies: ['bx bxl-tailwind-css', 'devicon-rails-plain colored', 'devicon-postgresql-plain-wordmark', 'bx bxl-react'],
    description: 'Built a React and Rails (ESBuild) BugTracker app for managing projects, assigning tasks, and tracking bugs and features.',
    livelink: '',
    sourcelink: '',
  },
];
export default projectData;
